# Generated by Django 5.0.7 on 2024-11-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_remove_user_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('REGULAR', 'Regular User'), ('ENGINEER', 'Engineer')], db_index=True, default='REGULAR', max_length=20),
        ),
    ]
